Importing Libraries

In [5]:
import pandas as pd
import os

Just making directory calling easier and more pretty

In [7]:
os.chdir('C:/Users/wissam_T/Desktop/slef improvement courses/ just random ai taining shit/online ai training course')

adding the dataset

In [21]:
book_df = pd.read_csv('datasets/amazon books datasets/Amazon_books_dataset.csv')

In [22]:
book_df.head()

,Unnamed: 0,Title,Author,Main Genre,Sub Genre,Type,Price,Rating,No. of People rated,URLs
0,0,The Complete Novel of Sherlock Holmes,Arthur Conan Doyle,"Arts, Film & Photography",Cinema & Broadcast,Paperback,₹169.00,4.4,19923.0,https://www.amazon.in/Complete-Novels-Sherlock...
1,1,Black Holes (L) : The Reith Lectures [Paperbac...,Stephen Hawking,"Arts, Film & Photography",Cinema & Broadcast,Paperback,₹99.00,4.5,7686.0,https://www.amazon.in/Black-Holes-Lectures-Ste...
2,2,The Kite Runner,Khaled Hosseini,"Arts, Film & Photography",Cinema & Broadcast,Kindle Edition,₹175.75,4.6,50016.0,https://www.amazon.in/Kite-Runner-Khaled-Hosse...
3,3,Greenlights: Raucous stories and outlaw wisdom...,Matthew McConaughey,"Arts, Film & Photography",Cinema & Broadcast,Paperback,₹389.00,4.6,32040.0,https://www.amazon.in/Greenlights-Raucous-stor...
4,4,The Science of Storytelling: Why Stories Make ...,Will Storr,"Arts, Film & Photography",Cinema & Broadcast,Paperback,₹348.16,4.5,1707.0,https://www.amazon.in/Science-Storytelling-Wil...

In [30]:
book_df.columns

Index(['Unnamed: 0', 'Title', 'Author', 'Main Genre', 'Sub Genre', 'Type',
       'Price', 'Rating', 'No. of People rated', 'URLs'],
      dtype='object')

In [31]:
book_df.describe(include = 'all')

,Unnamed: 0,Title,Author,Main Genre,Sub Genre,Type,Price,Rating,No. of People rated,URLs
count,7928.0000,7928,7907,7928,7928,7928,7928,7928.000000,7928.000000,7928
unique,NaN,5740,3686,30,151,33,1676,NaN,NaN,7828
top,NaN,AI Sports Beautiful Women Photo Collection for...,Wonder House Books,Children's Books,Fantasy,Paperback,₹449.00,NaN,NaN,https://www.amazon.in/Mahatma-Gandhi-Autobiogr...
freq,NaN,13,389,1450,150,4200,229,NaN,NaN,2
mean,3963.5000,NaN,NaN,NaN,NaN,NaN,NaN,4.260797,6479.312941,NaN
std,2288.7608,NaN,NaN,NaN,NaN,NaN,NaN,0.910659,22082.884343,NaN
min,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN
25%,1981.7500,NaN,NaN,NaN,NaN,NaN,NaN,4.300000,63.000000,NaN
50%,3963.5000,NaN,NaN,NaN,NaN,NaN,NaN,4.500000,499.000000,NaN
75%,5945.2500,NaN,NaN,NaN,NaN,NaN,NaN,4.600000,2905.250000,NaN
max,7927.0000,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,500119.000000,NaN

In [38]:
book_df.isna().sum()

Unnamed: 0              0
Title                   0
Author                 21
Main Genre              0
Sub Genre               0
Type                    0
Price                   0
Rating                  0
No. of People rated     0
URLs                    0
dtype: int64

In [39]:
null_data = book_df[book_df.isnull().any(axis=1)]
null_data

,Unnamed: 0,Title,Author,Main Genre,Sub Genre,Type,Price,Rating,No. of People rated,URLs
461,461,Peppa Pig : Peppa's Super Noisy Sound Bo,NaN,Children's Books,Animals & Pets,Hardcover,₹477.00,4.5,7424.0,https://www.amazon.in/Peppa-Pig-Peppas-Super-N...
466,466,Ladybird Big Noisy Book : Farm Hullaball,NaN,Children's Books,Animals & Pets,Board book,₹481.00,4.6,2357.0,https://www.amazon.in/Ladybird-Big-Noisy-Book-...
480,480,Peppa Pig Super Stickers Activity Book,NaN,Children's Books,Animals & Pets,Paperback,₹259.00,4.6,3609.0,https://www.amazon.in/Peppa-Pig-Super-Stickers...
486,486,Peppa Pig: Little Library [Board book] Peppa Pig,NaN,Children's Books,Animals & Pets,Board book,₹200.00,4.3,23598.0,https://www.amazon.in/Peppa-Pig-Little-Library...
597,597,GERONIMO STILTON: THEA STILTON AND THE MYSTERY...,NaN,Children's Books,Comics & Graphic Novels,Paperback,₹225.00,4.6,1806.0,https://www.amazon.in/GERONIMO-STILTON-THEA-MY...
713,713,GERONIMO STILTON: THEA STILTON AND THE MYSTERY...,NaN,Children's Books,Crime & Thriller,Paperback,₹225.00,4.6,1806.0,https://www.amazon.in/GERONIMO-STILTON-THEA-MY...
1015,1015,Baby Touch: Tummy Time [Board book] Ladybird,NaN,Children's Books,"Games, Toys & Activities",Board book,₹242.00,4.6,2131.0,https://www.amazon.in/Baby-Touch-Tummy-Time/dp...
1028,1028,Peppa Pig : Peppa's Super Noisy Sound Bo,NaN,Children's Books,"Games, Toys & Activities",Hardcover,₹477.00,4.5,7424.0,https://www.amazon.in/Peppa-Pig-Peppas-Super-N...
1036,1036,Ladybird Big Noisy Book : Farm Hullaball,NaN,Children's Books,"Games, Toys & Activities",Board book,₹481.00,4.6,2357.0,https://www.amazon.in/Ladybird-Big-Noisy-Book-...
1104,1104,Baby Touch: Tummy Time [Board book] Ladybird,NaN,Children's Books,Growing Up & Facts of Life,Board book,₹242.00,4.6,2131.0,https://www.amazon.in/Baby-Touch-Tummy-Time/dp...
1180,1180,"Geronimo Stilton Cavemice #3: Help, Im in Hot ...",NaN,Children's Books,Historical Fiction,Paperback,₹227.00,4.4,216.0,https://www.amazon.in/Cavemice-Help-Lava-Geron...
1280,1280,Peppa Pig: Happy Birthday! (Sound Book) [Board...,NaN,Children's Books,Holidays & Celebrations,Paperback,₹315.00,4.4,2656.0,https://www.amazon.in/Peppa-Pig-Happy-Birthday...
1385,1385,Baby Touch: Tummy Time [Board book] Ladybird,NaN,Children's Books,Interactive & Activity Books,Board book,₹242.00,4.6,2131.0,https://www.amazon.in/Baby-Touch-Tummy-Time/dp...
1478,1478,Baby Touch: Tummy Time [Board book] Ladybird,NaN,Children's Books,Literature & Fiction,Board book,₹242.00,4.6,2131.0,https://www.amazon.in/Baby-Touch-Tummy-Time/dp...
1576,1576,GERONIMO STILTON: THEA STILTON AND THE MYSTERY...,NaN,Children's Books,Mysteries & Curiosities,Paperback,₹225.00,4.6,1806.0,https://www.amazon.in/GERONIMO-STILTON-THEA-MY...
1616,1616,Baby Touch: Tummy Time [Board book] Ladybird,NaN,Children's Books,Picture Books,Board book,₹242.00,4.6,2131.0,https://www.amazon.in/Baby-Touch-Tummy-Time/dp...
1640,1640,Peppa Pig : Peppa's Super Noisy Sound Bo,NaN,Children's Books,Picture Books,Hardcover,₹477.00,4.5,7424.0,https://www.amazon.in/Peppa-Pig-Peppas-Super-N...
4217,4217,Bose: The Untold Story of an Inconvenien,NaN,Politics,Freedom & Security,Hardcover,₹699.00,4.8,812.0,https://www.amazon.in/Bose-Inconvenient-Nation...
4356,4356,Little Oxford English Dictionary | 9th Indian ...,NaN,Reference,Dictionaries & Thesauruses,Paperback,₹305.00,4.3,553.0,https://www.amazon.in/Little-Oxford-English-Di...
4393,4393,Dictionary of Literary Terms & Literary,NaN,Reference,Dictionaries & Thesauruses,Paperback,₹999.00,4.5,757.0,https://www.amazon.in/Penguin-Dictionary-Liter...
7702,7702,All the Bright Places,NaN,Teen & Young Adult,Romance,Paperback,₹301.00,4.6,20754.0,https://www.amazon.in/All-Bright-Places-Jennif...

In [40]:
print(null_data.shape)

(21, 10)